'use client';

import React, { useEffect, useState, Suspense } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Card } from '../../../components/ui/card';
import { Button } from '../../../components/ui/button';
import { api } from '../../../lib/api';

interface Invoice {
  id: string;
  invoiceNumber: string;
  planName: string;
  amount: number;
  gst: number;
  total: number;
  paymentDate: string;
  expiryDate: string;
  user: {
    email: string;
    firstName: string;
    lastName: string;
  };
}

function InvoiceContent() {
  const params = useParams();
  const router = useRouter();
  const invoiceId = params.id as string;

  const [invoice, setInvoice] = useState<Invoice | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchInvoice = async () => {
      if (!invoiceId) return;

      try {
        const response = await api.get<{ status: string; invoice: Invoice }>(`/invoice/${invoiceId}`);
        if (response.status === 'success' && response.invoice) {
          setInvoice(response.invoice);
        }
      } catch (err) {
        console.error('Invoice details pull error:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchInvoice();
  }, [invoiceId]);

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] space-y-4">
        <svg className="animate-spin h-10 w-10 text-brand-violet" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
        </svg>
        <span className="text-xs text-brand-slate font-mono">Syncing receipt log...</span>
      </div>
    );
  }

  if (!invoice) {
    return (
      <div className="text-center py-16 space-y-4 max-w-md mx-auto">
        <span className="text-3xl">⚠️</span>
        <h3 className="text-white font-display font-black text-lg">Invoice Not Found</h3>
        <p className="text-xs text-brand-slate">
          The requested invoice record does not exist or has not been generated by the admin team yet.
        </p>
        <Button variant="primary" onClick={() => router.push('/dashboard')} fullWidth>
          Go to Dashboard
        </Button>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto space-y-6 my-10 px-4 print:my-0 print:px-0">
      {/* Action Header (Hidden during print) */}
      <div className="flex justify-between items-center bg-brand-card/45 border border-brand-border p-4 rounded-2xl print:hidden">
        <Button variant="secondary" onClick={() => router.push('/dashboard')} className="text-xs py-1 px-4">
          ← Dashboard
        </Button>
        <Button variant="primary" onClick={handlePrint} className="text-xs py-1 px-4 font-bold">
          🖨️ Print / Download PDF
        </Button>
      </div>

      {/* Invoice Sheet */}
      <Card className="bg-white text-slate-800 p-8 md:p-12 border border-slate-200 rounded-3xl shadow-xl space-y-8 print:border-0 print:shadow-none print:p-0">
        
        {/* Top Segment */}
        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-6 pb-6 border-b border-slate-100">
          <div className="space-y-1">
            <h1 className="text-xl font-display font-black text-slate-900 tracking-wider">
              MAKEMISTAKES
            </h1>
            <p className="text-[10px] text-slate-500 font-mono leading-relaxed">
              MakeMistakes Platform Technologies Pvt Ltd<br />
              100 Innovation Lab Road, Silicon City, IN
            </p>
          </div>
          <div className="text-left sm:text-right space-y-1">
            <h3 className="text-lg font-display font-black text-slate-900 uppercase">
              Tax Invoice
            </h3>
            <span className="text-xs font-mono text-slate-500 block">
              Invoice #: {invoice.invoiceNumber}
            </span>
            <span className="text-xs font-mono text-slate-500 block">
              Date: {new Date(invoice.paymentDate).toLocaleDateString()}
            </span>
          </div>
        </div>

        {/* Client & Plan Info */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 pb-6 border-b border-slate-100 text-xs">
          <div className="space-y-1">
            <span className="text-[10px] uppercase font-mono text-slate-400 font-bold block">
              Billed To:
            </span>
            <h4 className="font-semibold text-slate-900">
              {invoice.user.firstName} {invoice.user.lastName}
            </h4>
            <p className="text-slate-500 font-mono">{invoice.user.email}</p>
          </div>
          <div className="space-y-1 sm:text-right">
            <span className="text-[10px] uppercase font-mono text-slate-400 font-bold block">
              Subscription details:
            </span>
            <h4 className="font-semibold text-slate-900">
              {invoice.planName} (Active)
            </h4>
            <p className="text-slate-500 font-mono">
              Valid Till: {new Date(invoice.expiryDate).toLocaleDateString()}
            </p>
          </div>
        </div>

        {/* Itemised Breakdown Table */}
        <div className="space-y-3">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="border-b border-slate-200 text-slate-400 uppercase font-mono text-[9px]">
                  <th className="pb-2 font-bold">Item Description</th>
                  <th className="pb-2 text-right font-bold">Base Price</th>
                  <th className="pb-2 text-right font-bold">GST (18%)</th>
                  <th className="pb-2 text-right font-bold">Total</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-slate-100 text-slate-800">
                  <td className="py-4 font-medium">
                    {invoice.planName} Subscription
                  </td>
                  <td className="py-4 text-right font-mono">
                    ${invoice.amount.toFixed(2)}
                  </td>
                  <td className="py-4 text-right font-mono">
                    ${invoice.gst.toFixed(2)}
                  </td>
                  <td className="py-4 text-right font-mono font-semibold">
                    ${invoice.total.toFixed(2)}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Totals alignment */}
          <div className="flex justify-end pt-4">
            <div className="w-64 space-y-2 text-xs">
              <div className="flex justify-between text-slate-500">
                <span>Subtotal:</span>
                <span className="font-mono">${invoice.amount.toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-slate-500">
                <span>GST Tax (18%):</span>
                <span className="font-mono">${invoice.gst.toFixed(2)}</span>
              </div>
              <div className="border-t border-slate-200 my-2" />
              <div className="flex justify-between text-sm font-semibold text-slate-900">
                <span>Total Amount Paid:</span>
                <span className="font-mono text-base font-black">${invoice.total.toFixed(2)}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Footnote */}
        <div className="pt-8 border-t border-slate-100 text-center">
          <p className="text-[10px] text-slate-400 italic">
            Thank you for purchasing Pro membership. This is a computer-generated invoice and requires no physical signature.
          </p>
        </div>

      </Card>
    </div>
  );
}

export default function InvoicePage() {
  return (
    <div className="min-h-screen bg-brand-bg text-foreground print:bg-white print:text-black">
      <Suspense fallback={
        <div className="flex flex-col items-center justify-center min-h-[400px] space-y-4">
          <svg className="animate-spin h-10 w-10 text-brand-violet" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          <span className="text-xs text-brand-slate font-mono">Loading invoice details...</span>
        </div>
      }>
        <InvoiceContent />
      </Suspense>
    </div>
  );
}
